export { IonicButtonComponent } from './widgets/button/ionic-button.component';
export { IonicInputComponent } from './widgets/input/ionic-input.component';
export { IonicCheckboxComponent } from './widgets/checkbox/ionic-checkbox.component';
export { IonicFrameworkComponent } from './ionic-framework.component';
export { IonicTextareaComponent } from './widgets/textarea/ionic-textarea.component';
export { IonicSelectComponent } from './widgets/select/ionic-select.component';
export { IonicTabsComponent } from './widgets/tabs/ionic-tabs.component';
export { IonicToggleComponent } from './widgets/toggle/ionic-toggle.component';
export { IonicSectionComponent } from './widgets/section/ionic-section.component';
export { IonicFrameworkModule, IONIC_FRAMEWORK_COMPONENTS } from './ionic-framework.module';
export { IonicFramework } from './ionic-framework';